CSS_FILES := $(patsubst %.sass, %.css, \
    $(filter-out .static/css/fonts.sass, $(wildcard .static/css/*.sass)))

all: $(CSS_FILES)

%.css: %.sass .static/css/fonts.sass
	sass --style=compressed $< $@
